// Универсальный список моделей для VseGPT (актуально на июль 2024)
// Теперь каждая модель содержит type, endpoint и params согласно https://vsegpt.ru/Docs/API
export const allModels = [
  // 2025
  { name: 'DeepSeek V3', id: 'deepseek/deepseek-chat-0324-alt-fast', group: 'DeepSeek', badges: ['2025', 'Программирование', 'Reasoning', 'Новинка'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages','temperature','top_p','top_k','min_p'] },
  // 2024
  { name: 'GPT-4o', id: 'openai/gpt-4o', group: 'OpenAI', badges: ['🔥 Топ цена/качество', '2024', 'Мультимодальность', 'tools', 'Общие задачи'], type: 'vision', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'GPT-4.5 (Preview)', id: 'openai/gpt-4.5-preview', group: 'OpenAI', badges: ['💎 Самый мощный', '2024', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages','temperature','top_p','max_tokens','frequency_penalty','presence_penalty'] },
  { name: 'GPT-4.1', id: 'openai/gpt-4.1', group: 'OpenAI', badges: ['2024', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages','temperature','top_p','max_tokens','frequency_penalty','presence_penalty'] },
  { name: 'GPT-4 Turbo', id: 'openai/gpt-4-turbo', group: 'OpenAI', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages','temperature','top_p','max_tokens','frequency_penalty','presence_penalty'] },
  { name: 'Claude 4 Opus', id: 'anthropic/claude-opus-4', group: 'Anthropic', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Claude 4 Sonnet', id: 'anthropic/claude-sonnet-4', group: 'Anthropic', badges: ['2024', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Gemini 2.5 Pro', id: 'google/gemini-2.5-pro', group: 'Google', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Gemini 2.5 Flash', id: 'google/gemini-2.5-flash', group: 'Google', badges: ['2024', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Gemini 1.5 Pro', id: 'google/gemini-1.5-pro-latest', group: 'Google', badges: ['2024', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Perplexity Sonar Pro', id: 'perplexity/sonar-pro-online', group: 'Perplexity', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Perplexity Sonar Reasoning Pro', id: 'perplexity/sonar-reasoning-pro-online', group: 'Perplexity', badges: ['2024', 'Reasoning', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'DeepSeek Coder', id: 'deepseek/deepseek-coder', group: 'DeepSeek', badges: ['2024', 'Программирование', 'tools'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages','temperature','top_p','top_k','min_p'] },
  { name: 'Mistral Large', id: 'mistralai/mistral-large', group: 'Mistral', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Mixtral 8x7B', id: 'mistralai/mixtral-8x7b-instruct', group: 'Mistral', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Qwen2 72B', id: 'qwen/qwen2-72b-instruct', group: 'Qwen', badges: ['2024', 'Reasoning', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Llama 3 70B', id: 'meta/llama-3-70b-instruct', group: 'Llama', badges: ['2024', 'Reasoning', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Gemma 2 27B', id: 'google/gemma-2-27b-it', group: 'Gemma', badges: ['2024', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Grok-4', id: 'x-ai/grok-4', group: 'Grok', badges: ['2024', 'tools', 'Reasoning'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Cohere Command R+', id: 'cohere/command-r-plus', group: 'Cohere', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'YandexGPT 3', id: 'yandex/yandexgpt-3', group: 'Yandex', badges: ['2024', 'tools', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  // 2023
  { name: 'Claude 3 Opus', id: 'anthropic/claude-3-opus', group: 'Anthropic', badges: ['2023', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Claude 3 Sonnet', id: 'anthropic/claude-3-sonnet', group: 'Anthropic', badges: ['2023', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'GPT-3.5 Turbo', id: 'openai/gpt-3.5-turbo', group: 'OpenAI', badges: ['2023', 'Общие задачи'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages','temperature','top_p','max_tokens','frequency_penalty','presence_penalty'] },
  { name: 'DALL-E 3', id: 'openai/dall-e-3', group: 'OpenAI', badges: ['2023', 'Генерация изображений'], type: 'image', endpoint: '/v1/images/generations', params: ['model','prompt','n','size'] },
  { name: 'Grok-1', id: 'x-ai/grok-1', group: 'Grok', badges: ['2023', 'tools', 'Reasoning'], type: 'text', endpoint: '/v1/chat/completions', params: ['model','messages'] },
  { name: 'Stable Diffusion XL', id: 'stability/stable-diffusion-xl-1-0', group: 'Stable Diffusion', badges: ['2023', 'Генерация изображений'], type: 'image', endpoint: '/v1/images/generations', params: ['model','prompt','steps','width','height'] },
];

export const modelIdMap = {
  'GPT-4o': 'openai/gpt-4o',
  'GPT-4.5 (Preview)': 'openai/gpt-4.5-preview',
  'GPT-4.1': 'openai/gpt-4.1',
  'GPT-4 Turbo': 'openai/gpt-4-turbo',
  'GPT-3.5 Turbo': 'openai/gpt-3.5-turbo',
  'DALL-E 3': 'openai/dall-e-3',
  'Claude 4 Opus': 'anthropic/claude-opus-4',
  'Claude 4 Sonnet': 'anthropic/claude-sonnet-4',
  'Claude 3 Opus': 'anthropic/claude-3-opus',
  'Claude 3 Sonnet': 'anthropic/claude-3-sonnet',
  'Gemini 2.5 Pro': 'google/gemini-2.5-pro',
  'Gemini 2.5 Flash': 'google/gemini-2.5-flash',
  'Gemini 1.5 Pro': 'google/gemini-1.5-pro-latest',
  'Gemini 1.0 Pro': 'google/gemini-pro',
  'Gemini 1.0 Pro Vision': 'google/gemini-pro-vision',
  'Perplexity Sonar Pro': 'perplexity/sonar-pro-online',
  'Perplexity Sonar Reasoning Pro': 'perplexity/sonar-reasoning-pro-online',
  'DeepSeek V3': 'deepseek/deepseek-chat-0324-alt-fast',
  'DeepSeek Coder': 'deepseek/deepseek-coder',
  'Mistral Large': 'mistralai/mistral-large',
  'Mixtral 8x7B': 'mistralai/mixtral-8x7b-instruct',
  'Qwen2 72B': 'qwen/qwen2-72b-instruct',
  'Llama 3 70B': 'meta/llama-3-70b-instruct',
  'Gemma 2 27B': 'google/gemma-2-27b-it',
  'Grok-4': 'x-ai/grok-4',
  'Grok-1': 'x-ai/grok-1',
  'Stable Diffusion XL': 'stability/stable-diffusion-xl-1-0',
  'Cohere Command R+': 'cohere/command-r-plus',
  'YandexGPT 3': 'yandex/yandexgpt-3',
}; 